{
    'name': 'My Hospital Management',
    'version': '13.0.1.5.0',
    'category': 'Extra Tools',
    'summary': 'Module for managing alamin"s hospitals',
    'sequence': '10',
    'License': 'AGPL-3',
    'author': 'Alamin Islam',
    'Maintainer': 'Alamin Islam',
    'website': 'alamin.com',
    'depends': ['mail','base'],
    'demo': [],
    'data': [
        'views/patient.xml',
        'views/appointment.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'reports/report.xml',
        'reports/health_patient_card.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
